name: anime_tracker
description: "An app for recording your anime. Add tags and links to websites for viewing."
publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  file_picker: ^8.0.0
  image_picker: ^1.0.0
  url_launcher: ^6.2.0
  path_provider: ^2.1.0
  share_plus: ^10.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/l10n/ru.yaml
    - assets/l10n/en.yaml
    - assets/l10n/ua.yaml
    - assets/l10n/de.yaml
    - assets/l10n/fr.yaml
    - assets/l10n/es.yaml
    - assets/l10n/ja.yaml
    - assets/l10n/zh.yaml
    - assets/l10n/pt.yaml
    - assets/l10n/ko.yaml
    - assets/l10n/it.yaml
    - assets/l10n/nl.yaml
    
